// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    partial class IspitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Iverica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<float>("Duzina")
                        .HasColumnType("real");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("ProdavnicaID")
                        .HasColumnType("int");

                    b.Property<string>("Sara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Sirina")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("ProdavnicaID");

                    b.ToTable("Iverice");
                });

            modelBuilder.Entity("Models.Magacin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<float>("Duzina")
                        .HasColumnType("real");

                    b.Property<int?>("IvericaID")
                        .HasColumnType("int");

                    b.Property<string>("Sara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Sirina")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("IvericaID");

                    b.ToTable("Otpadci");
                });

            modelBuilder.Entity("Models.NarucenePloce", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<float>("Duzina")
                        .HasColumnType("real");

                    b.Property<int?>("IvericaID")
                        .HasColumnType("int");

                    b.Property<string>("Sara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Sirina")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("IvericaID");

                    b.ToTable("NarucenePloce");
                });

            modelBuilder.Entity("Models.Prodavnica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zarada")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Prodavnice");
                });

            modelBuilder.Entity("Models.Iverica", b =>
                {
                    b.HasOne("Models.Prodavnica", "Prodavnica")
                        .WithMany("Iverice")
                        .HasForeignKey("ProdavnicaID");

                    b.Navigation("Prodavnica");
                });

            modelBuilder.Entity("Models.Magacin", b =>
                {
                    b.HasOne("Models.Iverica", "Iverica")
                        .WithMany("Otpadci")
                        .HasForeignKey("IvericaID");

                    b.Navigation("Iverica");
                });

            modelBuilder.Entity("Models.NarucenePloce", b =>
                {
                    b.HasOne("Models.Iverica", "Iverica")
                        .WithMany("NarucenePloce")
                        .HasForeignKey("IvericaID");

                    b.Navigation("Iverica");
                });

            modelBuilder.Entity("Models.Iverica", b =>
                {
                    b.Navigation("NarucenePloce");

                    b.Navigation("Otpadci");
                });

            modelBuilder.Entity("Models.Prodavnica", b =>
                {
                    b.Navigation("Iverice");
                });
#pragma warning restore 612, 618
        }
    }
}
