// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    partial class IspitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Praznjenje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IspraznjenaKolicina")
                        .HasColumnType("int");

                    b.Property<int?>("RadnikID")
                        .HasColumnType("int");

                    b.Property<int?>("SilosID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RadnikID");

                    b.HasIndex("SilosID");

                    b.ToTable("Praznjenja");
                });

            modelBuilder.Entity("Models.Radnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ImePrezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Radnici");
                });

            modelBuilder.Entity("Models.Silos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Oznaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrenutnaPopunjenost")
                        .HasColumnType("int");

                    b.Property<int>("Vlaznost")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Silosi");
                });

            modelBuilder.Entity("Models.Praznjenje", b =>
                {
                    b.HasOne("Models.Radnik", "Radnik")
                        .WithMany("IspraznjeniSilosi")
                        .HasForeignKey("RadnikID");

                    b.HasOne("Models.Silos", "Silos")
                        .WithMany("IsprazniliSuMe")
                        .HasForeignKey("SilosID");

                    b.Navigation("Radnik");

                    b.Navigation("Silos");
                });

            modelBuilder.Entity("Models.Radnik", b =>
                {
                    b.Navigation("IspraznjeniSilosi");
                });

            modelBuilder.Entity("Models.Silos", b =>
                {
                    b.Navigation("IsprazniliSuMe");
                });
#pragma warning restore 612, 618
        }
    }
}
